### ISSUE TITLE
Segfault.

### ISSUE THREAD

**Issue by Achaean** [ManaPlus/ManaPlus#26] opened 2017-07-26 22:54 UTC
**Hi!** :-)
At "About" box, clicking the links "About The Mana World", or "About current server", produces a Segmentation Fault.

I compiled and installed v.1.7.7.22 locally (at Debian Jessie (oldstable) x64 KDE).
A.

**Comment by 4144** [comment] 2017-07-26 23:03
Hm, cant reproduce crash.
Can you run manaplus in gdb and crash it?
then type in gdb: bt
and show output?

**Comment by Achaean** [comment] 2017-07-27 11:33
OK! :-)
Here it is:

```
>gdb manaplus  
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from manaplus...done.
(gdb) run
Starting program: /usr/local/bin/manaplus 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[11:28:37.65] Generating config dir: /home/giorgos/.config/mana/mana
[11:28:37.65] Log file: /home/giorgos/.local/share/mana/manaplus.log
[11:28:37.65] init 1
[11:28:37.65] init 2
[11:28:37.65] init 3
[11:28:37.65] configuration file: /home/giorgos/.config/mana/mana/config.xml
[11:28:37.65] Warning: No configuration file (features.xml)
[11:28:37.65] init 4
[11:28:37.65] Configuration::write() writing configuration...
[11:28:37.65] bindtextdomain: /usr/local/share/locale
[11:28:37.65] locale: el_GR.UTF-8
[New Thread 0x7fffea308700 (LWP 4953)]
[New Thread 0x7fffe52c1700 (LWP 4954)]
[Thread 0x7fffe52c1700 (LWP 4954) exited]
[New Thread 0x7fffe52c1700 (LWP 4955)]
[New Thread 0x7fffe49be700 (LWP 4956)]
[New Thread 0x7fffdfdfc700 (LWP 4957)]
[Thread 0x7fffdfdfc700 (LWP 4957) exited]
[Thread 0x7fffe49be700 (LWP 4956) exited]

Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
36      ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
#1  0x00007ffff5adfb30 in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff5ae029c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)
    () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000000000821140 in HelpWindow::loadHelp (this=this@entry=0x12e61a0,
    helpFile="header\000e0\003\000\000\000\000\000\000\060\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\003\000\000\000>\n\000> client.\000bsite: 1\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\002\000\000\000//ma \000plus.o0\000\000\000\000\000\000\000a\003\000\000\000\000\000\000\310\071P\365\377\177\000\000\310\071P\365\377\177\000\000\377\377\377\377\000\000\000\000##3", ' ' <repeats 22 times>, "=== ABOUT MANAPLUS ===\000q\000\000\000\000\000\000\000"...) at gui/windows/helpwindow.cpp:129
#4  0x0000000000821368 in HelpWindow::handleLink (this=0x12e61a0,
    link="header\000e0\003\000\000\000\000\000\000\060\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\003\000\000\000>\n\000> client.\000bsite: 1\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\002\000\000\000//ma \000plus.o0\000\000\000\000\000\000\000a\003\000\000\000\000\000\000\310\071P\365\377\177\000\000\310\071P\365\377\177\000\000\377\377\377\377\000\000\000\000##3", ' ' <repeats 22 times>, "=== ABOUT MANAPLUS ===\000q\000\000\000\000\000\000\000"..., event=<optimized out>) at gui/windows/helpwindow.cpp:115
#5  0x0000000000539ac7 in StaticBrowserBox::mousePressed (this=0x7fffddc9c028, event=...) at gui/widgets/staticbrowserbox.cpp:326
#6  0x0000000000570c6e in Gui::distributeMouseEvent (this=0xe1ee40, source=<optimized out>, type=MouseEventType::PRESSED,
    button=<optimized out>, x=295, y=315, force=false, toSourceOnly=false) at gui/gui.cpp:923
#7  0x0000000000574a81 in Gui::handleMousePressed (this=0xe1ee40, mouseInput=...) at gui/gui.cpp:800
#8  0x0000000000576695 in Gui::handleMouseInput (this=this@entry=0xe1ee40) at gui/gui.cpp:1039
#9  0x0000000000576701 in Gui::logic (this=0xe1ee40) at gui/gui.cpp:317
#10 0x00000000006a3153 in Client::gameExec (this=0xcca110) at client.cpp:932
#11 0x0000000000628c4d in mainGui (argc=<optimized out>, argv=<optimized out>) at maingui.cpp:130
#12 0x00007ffff517fb45 in __libc_start_main (main=0x516980 <main(int, char**)>, argc=1, argv=0x7fffffffe168, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe158) at libc-start.c:287
#13 0x0000000000529428 in _start ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 4948] will be killed.

Quit anyway? (y or n) y
>

```

**Comment by 4144** [comment] 2017-07-27 13:08
look like it can be reproduced only in old compilers like gcc 4.9

Issue fixed in commit https://gitlab.com/manaplus/manaplus/commit/48942a35fdd7c1b1e7f5ab7833c74196a0f6c942

**Closed by 4144** 2017-07-27 13:08 UTC
